version: '3.8'

services:

  backend:
    build: ./ecommerce-backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db

  frontend:
    build: ./ecommerce-frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
